### PR TITLE
footer responsive

### PR DESCRIPTION
**Pull request by bj-jiwrajka**

### CODE REVIEW

**Review by byt3h3ad — APPROVED** [review]

**Review by byt3h3ad — APPROVED** [review]

**Comment by byt3h3ad** [comment]
we added social media logos but whose links will we add there?

**Comment by bj-jiwrajka** [comment]
> we added social media logos but whose links will we add there?

for now we can add the links of gdsc nit silchar chapter

**Comment by byt3h3ad** [comment]
why

**Comment by bj-jiwrajka** [comment]
> > we added social media logos but whose links will we add there?
> 
> for now we can add the links of gdsc nit silchar chapter

yes, great idea :)

**Pull request merged**
